language: node_js
node_js:
  - "10.1"
jobs:
  include:
    - stage: "Tests"
      name: "Install"
      script: npm run install:all-prod
      script: npm run build:client
    - stage: "Deploy"
      provider: script
      script: bash scripts/deploy.sh
      on:
        branch: nginx